<?php

return [
    'widget_types' => [
        'kpi',
        'bar',
        'line',
        'pie',
        'table',
        'map',
        'trend',
        'demographic',
        'team',
        'attendance',
        'welfare',
    ],

    'metrics' => [
        'members' => [
            'label' => 'Active members',
            'definition' => 'Count of members with active lifecycle status in scope.',
            'permission' => 'members.read',
            'supports_location' => false,
            'supports_demographics' => true,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'line', 'trend', 'table', 'demographic', 'pie'],
        ],
        'visitors' => [
            'label' => 'Visitors',
            'definition' => 'Visitors captured in the selected period.',
            'permission' => 'visitors.read',
            'supports_location' => false,
            'supports_demographics' => true,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'line', 'trend', 'table', 'demographic', 'pie'],
        ],
        'converts' => [
            'label' => 'Converts',
            'definition' => 'Members currently in the convert lifecycle stage.',
            'permission' => 'members.lifecycle.read',
            'supports_location' => false,
            'supports_demographics' => true,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table', 'demographic', 'pie'],
        ],
        'attendance' => [
            'label' => 'Attendance',
            'definition' => 'Attendance records captured in the selected period.',
            'permission' => 'attendance.read',
            'supports_location' => false,
            'supports_demographics' => false,
            'high_cardinality' => true,
            'visualizations' => ['kpi', 'bar', 'line', 'trend', 'table', 'attendance'],
        ],
        'teams' => [
            'label' => 'Service teams',
            'definition' => 'Active service teams and assignments in scope.',
            'permission' => 'teams.read',
            'supports_location' => false,
            'supports_demographics' => false,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table', 'team'],
        ],
        'volunteers' => [
            'label' => 'Volunteers',
            'definition' => 'Active volunteer profiles in scope.',
            'permission' => 'volunteers.read',
            'supports_location' => false,
            'supports_demographics' => false,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table', 'team'],
        ],
        'welfare' => [
            'label' => 'Welfare cases',
            'definition' => 'Open welfare cases and submissions in scope.',
            'permission' => 'welfare.reports.read',
            'supports_location' => true,
            'supports_demographics' => false,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table', 'welfare'],
        ],
        'care' => [
            'label' => 'Pastoral care',
            'definition' => 'Open pastoral care cases visible to the viewer.',
            'permission' => 'care.cases.read',
            'supports_location' => true,
            'supports_demographics' => false,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table'],
        ],
        'events' => [
            'label' => 'Events',
            'definition' => 'Upcoming published events in scope.',
            'permission' => 'events.read',
            'supports_location' => true,
            'supports_demographics' => false,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table', 'map'],
        ],
        'giving' => [
            'label' => 'Giving',
            'definition' => 'Reconciled contributions in the selected period.',
            'permission' => 'payments.giving.reports',
            'supports_location' => false,
            'supports_demographics' => false,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'line', 'trend', 'table'],
        ],
        'growth' => [
            'label' => 'Membership growth',
            'definition' => 'New member registrations in the selected period.',
            'permission' => 'members.read',
            'supports_location' => false,
            'supports_demographics' => true,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'line', 'trend', 'table', 'demographic'],
        ],
        'follow_up' => [
            'label' => 'Follow-ups',
            'definition' => 'Open follow-up assignments in scope.',
            'permission' => 'followups.read',
            'supports_location' => false,
            'supports_demographics' => false,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table'],
        ],
        'baptisms' => [
            'label' => 'Baptisms',
            'definition' => 'Recorded baptism milestones in the selected period.',
            'permission' => 'members.lifecycle.read',
            'supports_location' => false,
            'supports_demographics' => true,
            'high_cardinality' => false,
            'visualizations' => ['kpi', 'bar', 'table', 'demographic', 'pie'],
        ],
    ],

    'default_period_days' => 30,

    'max_widgets_per_dashboard' => 24,

    'validation' => [
        'pie_max_categories' => 8,
        'map_requires_location' => true,
    ],
];
