<?php

return [
    'performance_target_ms' => 3000,

    'disclosure' => [
        'min_cohort_size' => 5,
        'sensitive_sections' => ['welfare_open_cases', 'care_open_cases', 'giving_total_cents'],
    ],

    'stale_thresholds' => [
        'attendance_days' => 14,
        'giving_days' => 7,
        'communication_days' => 3,
    ],

    'period_presets' => [
        'weekly' => ['days' => 7, 'label' => 'Weekly'],
        'monthly' => ['days' => 30, 'label' => 'Monthly'],
        'quarterly' => ['days' => 90, 'label' => 'Quarterly'],
        'annual' => ['days' => 365, 'label' => 'Annual'],
        'custom' => ['label' => 'Custom range'],
    ],

    'reports' => [
        'membership' => [
            'label' => 'Membership summary',
            'category' => 'membership',
            'permission' => 'reports.standard.read',
            'definition' => 'Active members, new registrations, and lifecycle distribution for the selected branch and period.',
            'required_permissions' => ['members.read'],
            'period_presets' => ['weekly', 'monthly', 'quarterly', 'annual', 'custom'],
            'filters' => ['branch_id', 'lifecycle_status', 'lifecycle_stage'],
        ],
        'attendance' => [
            'label' => 'Attendance summary',
            'category' => 'attendance',
            'permission' => 'reports.standard.read',
            'definition' => 'Captured attendance records by status and gathering type within the selected period.',
            'required_permissions' => ['attendance.read'],
            'period_presets' => ['weekly', 'monthly', 'quarterly', 'annual', 'custom'],
            'filters' => ['branch_id', 'service_type', 'status'],
        ],
        'team' => [
            'label' => 'Team operations',
            'category' => 'team',
            'permission' => 'reports.standard.read',
            'definition' => 'Service teams, assignments, submitted team reports, and volunteer participation in scope.',
            'required_permissions' => ['teams.read', 'teams.reports.read'],
            'period_presets' => ['weekly', 'monthly', 'quarterly', 'annual', 'custom'],
            'filters' => ['branch_id', 'service_team_id'],
        ],
        'welfare' => [
            'label' => 'Welfare assistance',
            'category' => 'welfare',
            'permission' => 'reports.standard.read',
            'definition' => 'Welfare case volumes and status distribution with beneficiary identity minimized.',
            'required_permissions' => ['welfare.reports.read'],
            'period_presets' => ['weekly', 'monthly', 'quarterly', 'annual', 'custom'],
            'filters' => ['branch_id', 'request_type', 'status'],
            'sensitive' => true,
        ],
        'care' => [
            'label' => 'Pastoral care',
            'category' => 'care',
            'permission' => 'reports.standard.read',
            'definition' => 'Open and closed pastoral care cases visible to the viewer within scope.',
            'required_permissions' => ['care.cases.read'],
            'period_presets' => ['weekly', 'monthly', 'quarterly', 'annual', 'custom'],
            'filters' => ['branch_id', 'status'],
            'sensitive' => true,
        ],
        'communication' => [
            'label' => 'Communications',
            'category' => 'communication',
            'permission' => 'reports.standard.read',
            'definition' => 'Outbound communications and delivery outcomes for the selected period.',
            'required_permissions' => ['communications.read'],
            'period_presets' => ['weekly', 'monthly', 'quarterly', 'annual', 'custom'],
            'filters' => ['branch_id', 'purpose', 'status'],
        ],
        'management_weekly' => [
            'label' => 'Weekly management rollup',
            'category' => 'management',
            'permission' => 'reports.standard.read',
            'definition' => 'Cross-domain weekly operational summary using consistent metric definitions.',
            'required_permissions' => ['members.read', 'attendance.read'],
            'fixed_period_preset' => 'weekly',
            'period_presets' => ['weekly'],
            'filters' => ['branch_id'],
        ],
        'management_monthly' => [
            'label' => 'Monthly management rollup',
            'category' => 'management',
            'permission' => 'reports.standard.read',
            'definition' => 'Cross-domain monthly operational summary using consistent metric definitions.',
            'required_permissions' => ['members.read', 'attendance.read'],
            'fixed_period_preset' => 'monthly',
            'period_presets' => ['monthly'],
            'filters' => ['branch_id'],
        ],
        'management_quarterly' => [
            'label' => 'Quarterly management rollup',
            'category' => 'management',
            'permission' => 'reports.standard.read',
            'definition' => 'Cross-domain quarterly operational summary using consistent metric definitions.',
            'required_permissions' => ['members.read', 'attendance.read'],
            'fixed_period_preset' => 'quarterly',
            'period_presets' => ['quarterly'],
            'filters' => ['branch_id'],
        ],
        'management_annual' => [
            'label' => 'Annual management rollup',
            'category' => 'management',
            'permission' => 'reports.standard.read',
            'definition' => 'Cross-domain annual operational summary using consistent metric definitions.',
            'required_permissions' => ['members.read', 'attendance.read'],
            'fixed_period_preset' => 'annual',
            'period_presets' => ['annual'],
            'filters' => ['branch_id'],
        ],
    ],
];
